/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef kvstore_CONSTANTS_H
#define kvstore_CONSTANTS_H

#include "kvstore_types.h"

namespace kvstore {

class kvstoreConstants {
 public:
  kvstoreConstants();

};

extern const kvstoreConstants g_kvstore_constants;

} // namespace

#endif
