/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "kvstore_constants.h"

namespace kvstore {

const kvstoreConstants g_kvstore_constants;

kvstoreConstants::kvstoreConstants() {
}

} // namespace

